[template]
src = "solr/solr-log4j.properties.tpl"
dest = "/usr/local/tomcat/webapps/solr/WEB-INF/classes/log4j.properties"
uid = 1000
gid = 1000
mode = "0740"
keys = [
  "/solr/org/apache/zookeeper/log",
  "/solr/org/apache/hadoop/log",
  "/solr/org/apache/solr/update/logginginforstream",
  "/solr/root/logger"
]